name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Miniforge3
          miniforge-version: latest
          auto-update-conda: true

      - name: Install compilers
        run: |
            conda install c-compiler cxx-compiler

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Build
        run: |
          pip install nox
          nox -s build --force-pythons=${{ matrix.python-version }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.python-version }}
          path: build/wheelhouse/*

  test:
    needs: build
    name: Run the tests

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        pytest-marker: ["slow", "not slow"]
        session-name: ["test", "test-notebooks"]
        exclude:
          - session-name: "test-notebooks"
            python-version: 3.10
          - session-name: "test-notebooks"
            python-version: 3.11
          - session-name: "test-notebooks"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Miniforge3
          miniforge-version: latest
          auto-update-conda: true

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Install and test richdem engine
        run: |
          conda install richdem -c conda-forge
          python -c 'import _richdem'

      - uses: actions/download-artifact@v4
        name: Download build artifact
        with:
          name: build-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Test
        env:
          HYPOTHESIS_PROFILE: "ci"
          OPENTOPOGRAPHY_API_KEY: ${{ secrets.OPENTOPOGRAPHY_API_KEY }}
          MPLBACKEND: "Agg"
        run: |
          pip install nox
          nox --verbose -s ${{ matrix.session-name }} --force-pythons=${{ matrix.python-version }} -- -m '${{ matrix.pytest-marker }}' --path=*whl

      - name: Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.session-name == 'test' }}
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: py${{ matrix.python-version }}-${{ matrix.os }}-'${{ matrix.pytest-marker }}'
          debug: true

  coveralls_finish:
    needs: test
    runs-on: ububtu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
          debug: true
